require: rubocop-rspec
################################################################################
## Releasing the hounds in your local environment.
##
## Setup:
## $ gem install rubocop
##
## Run:
## $ rubocop ./path/to/file ./or/path/to/directory -c ./.hound.yml
##
################################################################################
AllCops:
  Include:
    - Rakefile
  Exclude:
    - app/data_generators/sipity/data_generators/**/*
    - db/**/*
    - bin/**/*
    - config/**/*
    - dragonfly/**/*
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'spec/support/sipity/command_repository_interface.rb'
    - 'spec/support/sipity/query_repository_interface.rb'
    - 'app/validators/open_for_starting_submissions_validator.rb'
    - 'app/forms/sipity/forms/form_builder.rb'
  RunRailsCops: false

LineLength:
  Description: 'Limit lines to 140 characters.'
  Max: 140
  Enabled: true

AlignParameters:
  Description: >-
                 Align the parameters of a method call if they span more
                 than one line.
  Enabled: true

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: true
  Exclude:

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
    - spec/**/*
    - lib/**/version.rb

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:

Metrics/AbcSize:
  Enabled: true
  Max: 12
  Exclude:

Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

EmptyLinesAroundBlockBody:
  Enabled: false

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: trailing
  Enabled: true

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()
  Enabled: true

RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: false

StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false
